# Generated by Django 2.2.10 on 2020-04-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialized_paths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='tree_path',
            field=models.CharField(db_index=True, editable=False, max_length=255, verbose_name='path'),
        ),
    ]
